include_guard(GLOBAL)

include(MpiLabSanitizers)
include(MpiLabWarnings)

option(BUILD_SHARED_LIBS "Build shared libraries instead of static libraries." OFF)
option(MPILAB_BUILD_TESTS "Build the mpilab test suite." ${PROJECT_IS_TOP_LEVEL})
option(MPILAB_ENABLE_WARNINGS "Enable strict compiler warnings for mpilab targets." ON)
option(MPILAB_WARNINGS_AS_ERRORS "Treat compiler warnings as errors." OFF)
option(MPILAB_ENABLE_IPO "Enable interprocedural optimization for optimized builds." OFF)
option(MPILAB_ENABLE_MPI "Try to link mpilab against MPI CXX support." ON)
option(MPILAB_REQUIRE_MPI "Fail configuration if MPI CXX support is unavailable." OFF)
option(MPILAB_ENABLE_CLANG_TIDY "Run clang-tidy during compilation when available." OFF)
option(MPILAB_ENABLE_CPPCHECK "Run cppcheck during compilation when available." OFF)
option(MPILAB_ENABLE_COVERAGE "Enable coverage instrumentation for GCC/Clang debug builds." OFF)
option(MPILAB_ENABLE_UNITY_BUILD "Enable CMake unity builds for faster local compilation." OFF)

set(MPILAB_SANITIZERS "" CACHE STRING "Semicolon-separated sanitizers: address;undefined;thread;leak.")
set_property(CACHE MPILAB_SANITIZERS PROPERTY STRINGS "" "address" "undefined" "address;undefined" "thread" "leak")

function(mpilab_setup_project_options)
    set(CMAKE_EXPORT_COMPILE_COMMANDS ON CACHE BOOL "Export compile_commands.json." FORCE)

    if(NOT CMAKE_BUILD_TYPE AND NOT CMAKE_CONFIGURATION_TYPES)
        set(CMAKE_BUILD_TYPE "Debug" CACHE STRING "Build type." FORCE)
        set_property(CACHE CMAKE_BUILD_TYPE PROPERTY STRINGS Debug Release RelWithDebInfo MinSizeRel)
    endif()

    set(CMAKE_CXX_STANDARD 20 CACHE STRING "C++ standard used by mpilab." FORCE)
    set(CMAKE_CXX_STANDARD_REQUIRED ON CACHE BOOL "Require the selected C++ standard." FORCE)
    set(CMAKE_CXX_EXTENSIONS OFF CACHE BOOL "Disable compiler-specific C++ extensions." FORCE)

    if(MPILAB_ENABLE_UNITY_BUILD)
        set(CMAKE_UNITY_BUILD ON CACHE BOOL "Enable unity build." FORCE)
    endif()

    if(MPILAB_ENABLE_CLANG_TIDY)
        find_program(MPILAB_CLANG_TIDY_EXE NAMES clang-tidy)
        if(MPILAB_CLANG_TIDY_EXE)
            set(CMAKE_CXX_CLANG_TIDY "${MPILAB_CLANG_TIDY_EXE}" CACHE STRING "clang-tidy command." FORCE)
        else()
            message(WARNING "MPILAB_ENABLE_CLANG_TIDY is ON, but clang-tidy was not found.")
        endif()
    endif()

    if(MPILAB_ENABLE_CPPCHECK)
        find_program(MPILAB_CPPCHECK_EXE NAMES cppcheck)
        if(MPILAB_CPPCHECK_EXE)
            set(CMAKE_CXX_CPPCHECK "${MPILAB_CPPCHECK_EXE};--enable=warning,style,performance,portability;--inline-suppr" CACHE STRING "cppcheck command." FORCE)
        else()
            message(WARNING "MPILAB_ENABLE_CPPCHECK is ON, but cppcheck was not found.")
        endif()
    endif()
endfunction()

function(mpilab_apply_common_target_options target)
    if(MPILAB_ENABLE_WARNINGS)
        mpilab_enable_warnings(${target})
    endif()

    if(MPILAB_SANITIZERS)
        mpilab_enable_sanitizers(${target} "${MPILAB_SANITIZERS}")
    endif()

    if(MPILAB_ENABLE_COVERAGE)
        mpilab_enable_coverage(${target})
    endif()

    if(MPILAB_ENABLE_IPO)
        include(CheckIPOSupported)
        check_ipo_supported(RESULT mpilab_ipo_supported OUTPUT mpilab_ipo_error)
        if(mpilab_ipo_supported)
            set_property(TARGET ${target} PROPERTY INTERPROCEDURAL_OPTIMIZATION_RELEASE ON)
            set_property(TARGET ${target} PROPERTY INTERPROCEDURAL_OPTIMIZATION_RELWITHDEBINFO ON)
        else()
            message(WARNING "IPO/LTO is not supported: ${mpilab_ipo_error}")
        endif()
    endif()
endfunction()
